In [56]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [57]:
import pandas as pd
df = pd.read_csv("insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [58]:
df.shape

(28, 3)

In [59]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(df[['age', 'affordibility']],df['bought_insurance'],test_size=0.2, random_state= 25)
X_train

age  affordibility
0    22              1
13   29              0
6    55              0
17   58              1
24   50              1
19   18              1
25   54              1
16   25              0
20   21              1
3    52              0
7    60              0
1    25              0
5    56              1
27   46              1
8    62              1
18   19              0
12   27              0
23   45              1
22   40              1
15   55              1
26   23              1
4    46              1

In [60]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [61]:
X_train_scaled

age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
27  0.46              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
26  0.23              1
4   0.46              1

In [62]:
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,), activation = "sigmoid", 
                       kernel_initializer='ones',
                       bias_initializer='zeros')
   
    
])
model.compile(optimizer = "adam",
              loss = "binary_crossentropy",
              metrics = "accuracy"
              )
model.fit(X_train_scaled, y_train, epochs =5000)

Epoch 1/5000


1/1 [==============================] - 0s 435ms/step - loss: 0.7113 - accuracy: 0.5000
Epoch 2/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.7110 - accuracy: 0.5000
Epoch 3/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.7106 - accuracy: 0.5000
Epoch 4/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.7102 - accuracy: 0.5000
Epoch 5/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.7098 - accuracy: 0.5000
Epoch 6/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.7094 - accuracy: 0.5000
Epoch 7/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.7091 - accuracy: 0.5000
Epoch 8/5000
1/1 [==============================] - 0s 7ms/step - loss: 0.7087 - accuracy: 0.5000
Epoch 9/5000
1/1 [==============================] - 0s 6ms/step - loss: 0.7083 - accuracy: 0.5000
Epoch 10/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.7079 - accuracy: 0.5000
Epoch 11/5000
1/1 [===========

In [63]:
model.evaluate(X_test_scaled, y_test)

1/1 [==============================] - 0s 107ms/step - loss: 0.3550 - accuracy: 1.0000


[0.3549776077270508, 1.0]

In [64]:
X_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [65]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 62ms/step


array([[0.7054848 ],
       [0.3556957 ],
       [0.16827832],
       [0.47801185],
       [0.7260696 ],
       [0.8294983 ]], dtype=float32)

In [66]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [67]:
coef, intercept = model.get_weights()
coef, intercept

(array([[5.060863 ],
        [1.4086521]], dtype=float32),
 array([-2.913703], dtype=float32))

In [68]:
import math
def sigmoid(x):
    return 1 / (1+ math.exp(-x))
sigmoid (18)

0.9999999847700205

In [69]:
def prediction_function(age,affordability):
    weighted_sum= coef[0]*age + coef[1]*affordability + intercept
    return sigmoid(weighted_sum)
    
    

In [70]:
prediction_function(.26,0)

0.1682783220980067

In [71]:
def log_loss (y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1+y_true)*np.log(1-y_predicted_new))

In [72]:
def sigmoid_numpy(x):
    return 1 / (1+np.exp(-x))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [ ]:
class myNN:
    def __init__(self):
        pass
    def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    # w1, w2, bias
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)    
    
    for i in range (epochs):
       weighted_sum = w1*age+w2 * affordability + bias
       y_predicted = sigmoid_numpy(weighted_sum)
       loss = log_loss (y_true, y_predicted)
       w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
       w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))
       bias_d = np.mean(y_predicted - y_true)
       
       w1= w1 - rate * w1d
       w2= w2 -rate * w2d
       bias= bias -rate * bias_d 
       
       print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
       if loss<= loss_thresold:
           break
    return w1, w2,bias 

In [73]:
def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    # w1, w2, bias
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)    
    
    for i in range (epochs):
       weighted_sum = w1*age+w2 * affordability + bias
       y_predicted = sigmoid_numpy(weighted_sum)
       loss = log_loss (y_true, y_predicted)
       w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
       w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))
       bias_d = np.mean(y_predicted - y_true)
       
       w1= w1 - rate * w1d
       w2= w2 -rate * w2d
       bias= bias -rate * bias_d 
       
       print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
       if loss<= loss_thresold:
           break
    return w1, w2,bias 

In [74]:
gradient_descent(X_train_scaled['age'], X_train_scaled['affordibility'], y_train, 1000, 0.4631 )

Epoch:0, w1:0.974907633470177, w2:0.948348125394529, bias:-0.11341867736368583, loss:2.284986948697116
Epoch:1, w1:0.9556229728273669, w2:0.9058873696677865, bias:-0.2122349122718517, loss:2.1240952413409477
Epoch:2, w1:0.9416488476693794, w2:0.8719790823960313, bias:-0.29775789977965383, loss:1.994560364984746
Epoch:3, w1:0.9323916996249162, w2:0.8457541517722915, bias:-0.37150947240035115, loss:1.891399666695663
Epoch:4, w1:0.9272267472726993, w2:0.8262362885332687, bias:-0.4350664302689159, loss:1.8098249065273209
Epoch:5, w1:0.9255469396815343, w2:0.8124402814952774, bias:-0.4899449005893882, loss:1.7455769185899312
Epoch:6, w1:0.9267936114129968, w2:0.8034375029757677, bias:-0.5375299543522855, loss:1.6950621233797691
Epoch:7, w1:0.93047170420295, w2:0.7983920007454487, bias:-0.5790424270894964, loss:1.655353649618037
Epoch:8, w1:0.9361540784567943, w2:0.7965748796787705, bias:-0.6155315088627656, loss:1.6241206935089283
Epoch:9, w1:0.9434791243557358, w2:0.7973647616854131, bias:

(8.27023951605617, 1.6332228396255535, -4.425953608965704)

In [75]:
coef, intercept

(array([[5.060863 ],
        [1.4086521]], dtype=float32),
 array([-2.913703], dtype=float32))

## Implement Neural Network

In [86]:
class myNN:
    def __init__(self):
        self.w1 = 1
        self.w2 = 1
        self.bias = 0
    
    
    def fit(self,X,y,epochs, loss_thresold):
        self.w1, self.w2, self.bias = self.gradient_descent(X['age'], X['affordibility'], y, epochs, loss_thresold)
    
    def predict(self, X_test):
        weighted_sum = self.w1 *  X_test['age'] + self.w2 *  X_test['affordibility'] + self.bias
        return sigmoid_numpy
    
    def gradient_descent(self, age, affordability, y_true, epochs, loss_thresold):
        # w1, w2, bias
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)    
        
        for i in range (epochs):
            weighted_sum = w1*age+w2 * affordability + bias
            y_predicted = sigmoid_numpy(weighted_sum)
            loss = log_loss (y_true, y_predicted)
            w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
            w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))
            bias_d = np.mean(y_predicted - y_true)
            
            w1= w1 - rate * w1d
            w2= w2 -rate * w2d
            bias= bias -rate * bias_d 
            
            if i%50 ==0:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
            
            if loss<= loss_thresold:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
                break
        return w1, w2,bias 

In [87]:
customModel = myNN()
customModel.fit(X_train_scaled, y_train, epochs=1000, loss_thresold=0.4631)

Epoch:0, w1:0.974907633470177, w2:0.948348125394529, bias:-0.11341867736368583, loss:2.284986948697116
Epoch:50, w1:1.503319554173139, w2:1.108384790367645, bias:-1.2319047301235464, loss:1.5267171806660154
Epoch:100, w1:2.200713131760032, w2:1.2941584023238903, bias:-1.6607009122062801, loss:1.5576052030066398
Epoch:150, w1:2.8495727769689085, w2:1.3696895491572747, bias:-1.986105845859897, loss:1.5853550250253143
Epoch:200, w1:3.443016970881803, w2:1.4042218624465033, bias:-2.2571369883752723, loss:1.6117829184091095
Epoch:250, w1:3.982450494649576, w2:1.4239127329321233, bias:-2.494377365971801, loss:1.637627128049113
Epoch:300, w1:4.472179522095915, w2:1.438787986553552, bias:-2.707387811922373, loss:1.6629747393657035
Epoch:350, w1:4.917245868007634, w2:1.4525660781176122, bias:-2.901176333556766, loss:1.6876966418693675
Epoch:400, w1:5.3225621674147305, w2:1.4664810071905663, bias:-3.0787595797907787, loss:1.711634009500198
Epoch:450, w1:5.69260053360137, w2:1.4808112468106691, b

In [89]:
coef, intercept

(array([[5.060863 ],
        [1.4086521]], dtype=float32),
 array([-2.913703], dtype=float32))

In [90]:
customModel.predict(X_test_scaled)

<function __main__.sigmoid_numpy(x)>

In [91]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 44ms/step


array([[0.7054848 ],
       [0.3556957 ],
       [0.16827832],
       [0.47801185],
       [0.7260696 ],
       [0.8294983 ]], dtype=float32)